name: turbela
recipe: laravel
config:
  php: "8.0"
  composer_version: 2
  composer: []
  webroot: backend/public
  via: nginx
  config:
    vhosts: .lando/default.conf.tpl
services:
  database:
    config:
      database: .lando/mysql.cnf
  client:
    port: false
    type: node:16
    build:
      - yarn
      - cd /app/client && yarn
    command: cd /app/client && yarn dev
    scanner: false
  appserver:
    build:
      - composer install
      - cd /app/backend && composer install
      - cd /app/backend && yarn
      - bash /app/.lando/no_env_setup.sh
    build_as_root:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sh -
      - apt-get install -y nodejs build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - npm install --global yarn
tooling:
  yarn:
    service: client
    cmd: yarn
  quasar:
    service: client
    cmd: npx quasar
    dir: /app/client
  extras:
    service: client
    cmd: node scripts/lando-extras/extras.js
    dir: /app
