// This file is generated by the `generate:schema` artisan command

export {}
export type AbilityName = 
'*:*' |
'view:User' |
'impersonate:User' |
'assign-roles:User' |
'assign-badge:User' |
'create:User' |
'search:User' |
'update:User' |
'create:Badge' |
'edit:Badge' |
'search:Badge' |
'create:Plan' |
'update:Plan' |
'index:Plan' |
'index:Feature' |
'create:Feature' |
'create:Terminal' |
'index:Terminal' |
'delete:Terminal' |
'create:Overlay' |
'index:Overlay' |
'delete:Overlay' |
'view:Overlay' |
'update:Overlay' |
'search:Locator' |
'create:Locator' |
'create:Course' |
'update:Course' |
'delete:Course' |
'index:Course' |
'view:Course' |
'update-admin-settings' |
'update-general-settings' |
'query-admin-settings' |
'update-payment-settings' |
'view-horizon' |
'index:Volunteer' |
'update:Volunteer' |
'update:VolunteerHour' |
'review:VolunteerHour' |
'view:Volunteer'
