services:
  cypress:
    type: node
    overrides:
      image: "cypress/included:6.3.0"
tooling:
  cypress:
    service: cypress
    env:
      ELECTRON_ENABLE_LOGGING: "false"
    dir: /app/client
    cmd: cypress
