#!/bin/bash

php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan event:cache
cp -r vendor/laravel/horizon/public/* storage/horizon/
php artisan migrate --force
docker-php-entrypoint php-fpm
